apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      # ensure that sys-hc will be deployed to all nodes
      tolerations:
      - operator: "Exists"
      containers:
      - name: {{ .Values.service.name }}
        image: {{ .Values.image.repository }}:{{ .Chart.Version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ .Values.volumes.system_hc_host_mount_path }}
          name: host-root-directory
        env:
        - name: SYS_HC_HOST_PATH
          value: {{ .Values.env.system_hc_host_path }}
        - name: AWS_EBS_MOUNTS_PATH
          value: {{ .Values.env.aws_ebs_mounts_path }}
        - name: MOUNTS_THRESHOLD_PERCENT
          value: "{{ .Values.env.mounts_threshold_percent }}"
        - name: ROOT_DISK_THRESHOLD_PERCENT
          value: "{{ .Values.env.root_disk_threshold_percent }}"
        - name: NTP_TIME_DRIFT
          value: {{ .Values.env.ntp_time_drift }}
        - name: NTP_POLLING_PERIOD
          value: {{ .Values.env.ntp_polling_period }}
        - name: K8S_API_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: cluster-facts
              key: cluster_api_url
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: host-root-directory
        hostPath:
          path:  {{ .Values.volumes.system_hc_host_volume_path}}
