# Default values for system-healthcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "true"
  isDaemon: "true"
eksCluster: false
image:
  repository: coco/coco-system-healthcheck
  pullPolicy: IfNotPresent
env:
    system_hc_host_path: "host_dir"
    aws_ebs_mounts_path: "/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws"
    mounts_threshold_percent: "10"
    root_disk_threshold_percent: "20"
    ntp_time_drift: "2s"
    ntp_polling_period: "1m"
volumes:
    system_hc_host_mount_path: /host_dir
    system_hc_host_volume_path: /
resources:
  limits:
    memory: 20Mi
  requests:
    memory: 8Mi


eksCluster: false
