# Default values for system-healthcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "true"
  isDaemon: "true"
image:
  repository: coco/coco-system-healthcheck
  pullPolicy: IfNotPresent
env:
    system_hc_host_path: "host_dir"
    ntp_time_drift: "2s"
    ntp_polling_period: "1m"
volumes:
    system_hc_host_mount_path: /host_dir
    system_hc_host_volume_path: /
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
